
# html lang
language: zh-CN

# header
site_brand_name: 猫的小窝

logo_image:
  enable: false
  image_path: /logo.png # path to your logo image

menu:
  首页: /
  归档: /archives/
  画廊: /categories/gallery/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/menu.js

# favicon
favicon: /favicon.ico

date_format: MMM D, YYYY

# profile
profile:
  title: 猫的小窝
  body: "「请别哭泣，爱与热忱会生长如昔」"
  image: https://s41.ax1x.com/2026/04/26/pehYviF.jpg 

  links:
    归档: /archives/
    标签: /tag/

# footer
footer:
  copyright_info:
    enable: true
    author: 除有特殊声明外，本站文章均采用 署名—相同方式共享 4.0 协议国际版 授权

  powered_by: # Powered by Hexo & Frame
    enable: true

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: true

# comments: support disqus and valine
valine: # valine setup guide: https://valine.js.org/quickstart.html
  enable: false
  appId: # Your valine app Id
  appKey: # Your valine app Key
  lang: 'en'
  placeholder: 'Say something'
  avatar: 'mp'
  meta: ['nick', 'mail']

disqus: # disqus setup guide: https://help.disqus.com/en/articles/1717056-publisher-quick-start-guide
  enable: false
  disqus_url: # your diqsuq url or shortname
  language: 'en'

# local search
local_search:
  enable: true
  place_holder: 随便搜搜吧
  trigger: auto # auto: trigger search whenever input changes
  top_n_per_article: 1 # show top n results per article, show all results by setting to -1
  unescape: false # unescape html strings to the readable one
  preload: false # reload the search data when the page loads, this will accelerate the search process

style:
  font-family:
    body: '"Noto Serif CJK"'